### ISSUE TITLE
Controller instantiation fails

### ISSUE THREAD

**Issue by nelsonblaha** [mohiva/play-silhouette#293]
I'm getting the following error at runtime:

```
java.lang.InstantiationException: controllers.ApplicationController
	at java.lang.Class.newInstance(Class.java:418) ~[na:1.8.0_11]
	at play.api.GlobalSettings$class.getControllerInstance(GlobalSettings.scala:198) ~[play_2.11-2.3.7.jar:2.3.7]
	at play.api.DefaultGlobal$.getControllerInstance(GlobalSettings.scala:206) ~[play_2.11-2.3.7.jar:2.3.7]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$43.apply(routes_routing.scala:198) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$43.apply(routes_routing.scala:198) ~[na:na]
Caused by: java.lang.NoSuchMethodException: controllers.ApplicationController.<init>()
```

I've been looking for a few weeks for suspicious differences between my app and the seed app, but I can't find any. My application controller looks like: 

```
class ApplicationController @Inject() (implicit val env: Environment[User, SessionAuthenticator])
  extends Silhouette[User, SessionAuthenticator] { ... }
```

Does anything come to mind? I've been stumped for a while on this, I know it's a terrible question but I have no other option at this point. The error message doesn't seem to indicate anything useful, unfortunately.

**Comment by akkie** [comment]
Do you use Java 8? Which version of Guice do you use? Maybe it is's equal to https://github.com/playframework/playframework/issues/3768

**Comment by nelsonblaha** [comment]
I use Scala 2.11. I ended up starting over from the seed, but if anyone else runs into this I suspect it was my bindings in SilhouetteModule.
