### ISSUE TITLE
access_token error when call facebook auth after upgrade from 3.0.0-SNAPSHOT to 3.0.0-RC1

### ISSUE THREAD

**Issue by ninege** [mohiva/play-silhouette#370]
Hi, 

I am using Silhouette in my project and it is great. 
But, when I just change this code in my build.sbt
  "com.mohiva" %% "play-silhouette" % "3.0.0-RC1"
to
  "com.mohiva" %% "play-silhouette" % "3.0.0-SNAPSHOT",
I got the following error.

I am using Play 2.4, I am not very sure if it was just me, I will do more investigation in my code.

<pre>

! @6mc87jalb - Internal server error, for (POST) [/account/authenticate/facebook] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[JsonParseException: Unrecognized token 'access_token': was expecting ('true', 'false' or 'null')
 at [Source: [B@12075bcb; line: 1, column: 14]]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:254) ~[play_2.11-2.4.0.jar:2.4.0]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180) ~[play_2.11-2.4.0.jar:2.4.0]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.0.jar:2.4.0]
        at play.api.mvc.WithFilters.onError(Filters.scala:93) [play_2.11-2.4.0.jar:2.4.0]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.0.jar:2.4.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [play-netty-server_2.11-2.4.0.jar:2.4.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:269) [play-netty-server_2.11-2.4.0.jar:2.4.0]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'access_token': was expecting ('true', 'false' or 'null')
 at [Source: [B@12075bcb; line: 1, column: 14]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487) ~[jackson-core-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518) ~[jackson-core-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3323) ~[jackson-core-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2482) ~[jackson-core-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:801) ~[jackson-core-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697) ~[jackson-core-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3602) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3520) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1870) ~[jackson-databind-2.5.3.jar:2.5.3]
        at play.api.libs.json.jackson.JacksonJson$.parseJsValue(JacksonJson.scala:223) ~[play-json_2.11-2.4.0.jar:2.4.0]
</pre>

**Comment by akkie** [comment]
In version 3.0 we have implemented the new Facebook 2.3 API version. In this version Facebook follows now the OAuth2 standard and returns Json for the access token. So all you have to do is to use the API version in your URL.

```
facebook.authorizationURL="https://graph.facebook.com/v2.3/oauth/authorize"
facebook.accessTokenURL="https://graph.facebook.com/v2.3/oauth/access_token"
```

**Comment by akkie** [comment]
Does this solve your issue?

**Comment by akkie** [comment]
I've added this to the Silhouette migration section.
