### ISSUE TITLE
A bit complex to specialize OAuth2 providers e.g. FacebookProvider due to abstract hardwiring

### ISSUE THREAD

**Issue by bravegag** [mohiva/play-silhouette#562]
For an application I'm working on and upon signing in using social, I require fetching couple of extra Facebook data fields e.g. birth date, gender and mobile phone. I was happy to find that the `com.mohiva.play.silhouette.impl.providers.oauth2.FacebookProvider` can be extended / specialized. However, this gets quickly very hairy: using the conventional approach i.e. inheriting and overriding the necessary members I get blocked because the `trait CommonSocialProfileBuilder` hardwires to the `CommonSocialProfile` case class instead of e.g. making it a generic constrained type to the trait `SocialProfile` (see compiler error at the bottom).

My solution ends up being a complete copy-paste of the `FacebookProvider` implementation because of Provider's hardwiring among its top abstract elements. I think that the design could be made simpler wanting to extend some provider profile with couple of extra needed fields. For example, I'd like to do the same with the `GoogleProvider` and then I'd need to duplicate this exercise over again. It also doesn't help that case classes can't be extended in Scala :(

Nevertheless, I think it should be easier to enable OAuth's specializations to introduce new fields and provide the necessary profile parsing. 

My initial naive specialized `FacebookProvider` implementation looked like this:

```
package modules

import com.mohiva.play.silhouette.api.LoginInfo
import com.mohiva.play.silhouette.api.util.HTTPLayer
import com.mohiva.play.silhouette.impl.providers.oauth2.FacebookProvider.ID
import com.mohiva.play.silhouette.impl.providers.{ CommonSocialProfileBuilder, OAuth2Info, OAuth2Settings, SocialProfile, SocialProfileBuilder, SocialProfileParser, SocialStateHandler }
import com.mohiva.play.silhouette.impl.providers.oauth2._
import org.joda.time.LocalDate
import org.joda.time.format.DateTimeFormat
import play.api.libs.json._

import scala.concurrent.Future

case class MyFacebookSocialProfile(
  loginInfo: LoginInfo,
  firstName: Option[String] = None,
  lastName: Option[String] = None,
  fullName: Option[String] = None,
  birthDate: Option[LocalDate],
  gender: Option[String],
  email: Option[String] = None,
  phoneNumber: Option[String],
  avatarURL: Option[String] = None) extends SocialProfile

/**
 * The profile parser for the common social profile.
 */
class MyFacebookProfileParser extends SocialProfileParser[JsValue, MyFacebookSocialProfile, OAuth2Info] {
  val dateFormat = "yyyy-MM-dd"

  implicit val jodaDateReads = Reads[LocalDate](js =>
    js.validate[String].map[LocalDate](dtString =>
      LocalDate.parse(dtString, DateTimeFormat.forPattern(dateFormat))
    )
  )

  /**
   * Parses the social profile.
   *
   * @param json     The content returned from the provider.
   * @param authInfo The auth info to query the provider again for additional data.
   * @return The social profile from given result.
   */
  override def parse(json: JsValue, authInfo: OAuth2Info) = Future.successful {
    val userID = (json \ "id").as[String]
    val firstName = (json \ "first_name").asOpt[String]
    val lastName = (json \ "last_name").asOpt[String]
    val fullName = (json \ "name").asOpt[String]
    val birthDate = (json \ "birth_date").asOpt[LocalDate]
    val gender = (json \ "gender").asOpt[String]
    val avatarURL = (json \ "picture" \ "data" \ "url").asOpt[String]
    val email = (json \ "email").asOpt[String]
    val phoneNumber = (json \ "phone_number").asOpt[String]

    MyFacebookSocialProfile(
      loginInfo = LoginInfo(ID, userID),
      firstName = firstName,
      lastName = lastName,
      fullName = fullName,
      birthDate = birthDate,
      gender = gender,
      email = email,
      phoneNumber = phoneNumber,
      avatarURL = avatarURL)
  }
}

trait MyCommonSocialProfileBuilder extends CommonSocialProfileBuilder {
  self: SocialProfileBuilder =>

  /**
   * The type of the profile a profile builder is responsible for.
   */
  override type Profile = MyFacebookSocialProfile
}

class MyFacebookProvider(
  protected val httpLayer: HTTPLayer,
  protected val stateHandler: SocialStateHandler,
  val settings: OAuth2Settings)
  extends BaseFacebookProvider with MyCommonSocialProfileBuilder {
  /**
   * The type of this class.
   */
  override type Self = MyFacebookProvider

  /**
   * The profile parser implementation.
   */
  override val profileParser = new MyFacebookProfileParser

  /**
   * Gets a provider initialized with a new settings object.
   *
   * @param f A function which gets the settings passed and returns different settings.
   * @return An instance of the provider initialized with new settings.
   */
  override def withSettings(f: (Settings) => Settings) = new MyFacebookProvider(httpLayer, stateHandler, f(settings))
}

```

but it leads to the following compiler error due to the hardwiring to the `CommonSocialProfileBuilder` and `CommonSocialProfile`:
```
[error] /home/bravegag/code/play-silhouette-seed/app/modules/MyFacebookProvider.scala:74:17: overriding type Profile in trait CommonSocialProfileBuilder, which equals com.mohiva.play.silhouette.impl.providers.CommonSocialProfile;
[error]  type Profile has incompatible type
[error]   override type Profile = MyFacebookSocialProfile
[error]                 ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```
Then, I end up making a very exhausting duplication of the `FacebookProvider` implementation:
```
package modules

import com.mohiva.play.silhouette.api.LoginInfo
import com.mohiva.play.silhouette.api.util.HTTPLayer
import com.mohiva.play.silhouette.impl.exceptions.ProfileRetrievalException
import com.mohiva.play.silhouette.impl.providers.oauth2.FacebookProvider.{ API, ID, SpecifiedProfileError }
import com.mohiva.play.silhouette.impl.providers.{ OAuth2Info, OAuth2Provider, OAuth2Settings, SocialProfile, SocialProfileBuilder, SocialProfileParser, SocialProvider, SocialStateHandler }
import org.joda.time.LocalDate
import org.joda.time.format.DateTimeFormat
import play.api.libs.json._

import scala.concurrent.Future

case class MyFacebookSocialProfile(
  loginInfo: LoginInfo,
  firstName: Option[String] = None,
  lastName: Option[String] = None,
  fullName: Option[String] = None,
  birthDate: Option[LocalDate],
  gender: Option[String],
  email: Option[String] = None,
  phoneNumber: Option[String],
  avatarURL: Option[String] = None) extends SocialProfile

/**
 * The profile parser for the common social profile.
 */
class MyFacebookProfileParser extends SocialProfileParser[JsValue, MyFacebookSocialProfile, OAuth2Info] {
  val dateFormat = "yyyy-MM-dd"

  implicit val jodaDateReads = Reads[LocalDate](js =>
    js.validate[String].map[LocalDate](dtString =>
      LocalDate.parse(dtString, DateTimeFormat.forPattern(dateFormat))
    )
  )

  /**
   * Parses the social profile.
   *
   * @param json     The content returned from the provider.
   * @param authInfo The auth info to query the provider again for additional data.
   * @return The social profile from given result.
   */
  override def parse(json: JsValue, authInfo: OAuth2Info) = Future.successful {
    println(json.toString)

    val userID = (json \ "id").as[String]
    val firstName = (json \ "first_name").asOpt[String]
    val lastName = (json \ "last_name").asOpt[String]
    val fullName = (json \ "name").asOpt[String]
    val birthDate = (json \ "birth_date").asOpt[LocalDate]
    val gender = (json \ "gender").asOpt[String]
    val avatarURL = (json \ "picture" \ "data" \ "url").asOpt[String]
    val email = (json \ "email").asOpt[String]
    val phoneNumber = (json \ "phone_number").asOpt[String]

    MyFacebookSocialProfile(
      loginInfo = LoginInfo(ID, userID),
      firstName = firstName,
      lastName = lastName,
      fullName = fullName,
      birthDate = birthDate,
      gender = gender,
      email = email,
      phoneNumber = phoneNumber,
      avatarURL = avatarURL)
  }
}

trait MySocialProfileBuilder extends SocialProfileBuilder {
  self: SocialProvider =>

  /**
   * The type of the profile a profile builder is responsible for.
   */
  override type Profile = MyFacebookSocialProfile
}

class MyFacebookProvider(
  protected val httpLayer: HTTPLayer,
  protected val stateHandler: SocialStateHandler,
  val settings: OAuth2Settings)
  extends OAuth2Provider with MySocialProfileBuilder { // <<<<<<<<<<<<<<<< can't extend FacebookProvider
  /**
   * The type of this class.
   */
  override type Self = MyFacebookProvider

  /**
   * The content type to parse a profile from.
   */
  override type Content = JsValue

  /**
   * The provider ID.
   */
  override val id = ID

  /**
   * Defines the URLs that are needed to retrieve the profile data.
   */
  override protected val urls = Map("api" -> settings.apiURL.getOrElse(API))

  /**
   * Builds the social profile.
   *
   * @param authInfo The auth info received from the provider.
   * @return On success the build social profile, otherwise a failure.
   */
  override protected def buildProfile(authInfo: OAuth2Info): Future[Profile] = {
    httpLayer.url(urls("api").format(authInfo.accessToken)).get().flatMap { response =>
      val json = response.json
      (json \ "error").asOpt[JsObject] match {
        case Some(error) =>
          val errorMsg = (error \ "message").as[String]
          val errorType = (error \ "type").as[String]
          val errorCode = (error \ "code").as[Int]

          throw new ProfileRetrievalException(SpecifiedProfileError.format(id, errorMsg, errorType, errorCode))
        case _ => profileParser.parse(json, authInfo)
      }
    }
  }

  /**
   * The profile parser implementation.
   */
  override val profileParser = new MyFacebookProfileParser

  /**
   * Gets a provider initialized with a new settings object.
   *
   * @param f A function which gets the settings passed and returns different settings.
   * @return An instance of the provider initialized with new settings.
   */
  override def withSettings(f: (Settings) => Settings) = new MyFacebookProvider(httpLayer, stateHandler, f(settings))
}

/**
 * The companion object.
 */
object MyFacebookProvider {

  /**
   * The error messages.
   */
  val SpecifiedProfileError = "[Silhouette][%s] Error retrieving profile information. Error message: %s, type: %s, code: %s"

  /**
   * The Facebook constants.
   */
  val ID = "facebook"
  val API = "https://graph.facebook.com/v2.3/me?fields=name,first_name,last_name,picture,email&return_ssl_resources=1&access_token=%s"
}
```

**Comment by bravegag** [comment]
Never mind, my bad :D 

I should have done it like this:

```
trait MyCommonSocialProfileBuilder extends SocialProfileBuilder {
  self: SocialProvider =>

  /**
   * The type of the profile a profile builder is responsible for.
   */
  override type Profile = MyFacebookSocialProfile
}
```

**Comment by bravegag** [comment]
After wiring `MyFacebookProvider` in the `SilhouetteModule` like so it still doesn't work:

```
  @Provides
  def provideSocialProviderRegistry(
    facebookProvider: MyFacebookProvider,
    googleProvider: GoogleProvider,
    vkProvider: VKProvider,
    twitterProvider: TwitterProvider,
    xingProvider: XingProvider,
    yahooProvider: YahooProvider): SocialProviderRegistry = {

    SocialProviderRegistry(Seq(
      googleProvider,
      facebookProvider,
      twitterProvider,
      vkProvider,
      xingProvider,
      yahooProvider
    ))
  }

  @Provides
  def provideFacebookProvider(
    httpLayer: HTTPLayer,
    socialStateHandler: SocialStateHandler,
    configuration: Configuration): MyFacebookProvider = {

    new MyFacebookProvider(httpLayer, socialStateHandler, configuration.underlying.as[OAuth2Settings]("silhouette.facebook"))
  }
```
I get the runtime error:

```
[error] c.SocialAuthController - Unexpected provider error
com.mohiva.play.silhouette.api.exceptions.ProviderException: Cannot authenticate with unknown/unsupported social provider facebook!
	at controllers.SocialAuthController.$anonfun$authenticate$1(SocialAuthController.scala:60)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:489)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:487)
	at play.api.mvc.ActionBuilder$$anon$10.apply(Action.scala:426)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:98)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:184)
	at scala.util.Try$.apply(Try.scala:213)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:184)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
``` 

I think extending Silhouette with new providers is reasonable complexity-wise but accommodating specialization of the existing providers such as in this case is unreasonable complex.

**Comment by bravegag** [comment]
For reference, I got this working here:
https://github.com/bravegag/play-silhouette-seed

See here:
https://github.com/bravegag/play-silhouette-seed/blob/master/app/providers/MyFacebookProvider.scala

and here:
https://github.com/bravegag/play-silhouette-seed/blob/master/app/providers/MySocialProfileBuilder.scala

**Comment by akkie** [comment]
@bravegag Have you seen that the documentation has an example exactly for this case?

https://www.silhouette.rocks/docs/providers#section-social-profile-builders-and-parsers

You shouldn't extend the `FacebookProvider` directly. You must include the `BaseFacebookProvider`. From the documentation:

```scala
class CustomFacebookProvider(
  protected val httpLayer: HTTPLayer,
  protected val stateProvider: OAuth2StateProvider,
  val settings: OAuth2Settings)
  extends BaseFacebookProvider {
```

**Comment by bravegag** [comment]
@akkie Hi Christian! thanks! I didn't find / see this documentation, it is exactly what I needed. I will refactor my Seed according to this. Thank you again. 

btw Any progress on integrating the PRs?

**Comment by akkie** [comment]
I'm very busy with other things at the moment. Will see if I find the time on Sunday.

**Comment by bravegag** [comment]
@akkie we can organize a call or Skype if you need any help to speed up the PR merges. PM to my GH login at hotmail com.

**Comment by bravegag** [comment]
The Doc is outdated, the Doc doesn't include and is missing:
1. The social profile builder i.e. see the line `case Some(p: SocialProvider with CommonSocialProfileBuilder)` I don't use the "common".
2. Doesn't show how to override the URL that includes the extra parameters.

**Comment by akkie** [comment]
@bravegag What do you mean exactly? The social profile builder is documented: https://www.silhouette.rocks/docs/providers#section-social-profile-builders-and-parsers

If you find the documentation is outdated, it would be awesome if you could add your suggestions directly to the documentation, by creating an suggested edit.
